In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [8]:
df = pd.read_csv('solar_system.csv')

In [9]:
df.shape

(20, 11)

In [10]:
df = df.set_index("Attribute").T
df.index.name = "Planet"
df.reset_index(inplace=True)
df.columns.name = None

In [11]:
df.shape

(10, 21)

In [12]:
# shape before- (20,11), 20 rows, 11 columns, shape after- (10, 21), 10 rows, 21 columns

In [13]:
# df = df.set_index("Attribute").T makes "Attribute" the index then flips the rows and columns
# df.index.name = "Planet" names the index "Planet"
# df.reset_index(inplace=True) turns the index "Planet" into a normal column
# df.columns.name = None removes the column name

# because the column "attribute turns into an index rather than a column, then .T flips rows and columns, then we add a new column called planets

In [14]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [15]:
# Has units (16): mass (kg), diameter (km), density (kg/m^3), gravity (m/s^2), escape velocity (km/s), rotation period (hours), length of day (hours), distance from sun (km), perihelion (km), aphelion (km), orbital period (days), orbital velocity (km/s), Orbital Inclination (deg), Obliquity to Orbit (deg), Mean Temperature (C), Surface Pressure (bars) 
# Doesn't have units (5): Planet, Orbital Eccentricity, Number of Moons, Ring System?, Global Magnetic Field

In [16]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [17]:
for col in df.columns:
    print(col, df[col].apply(type).unique())

Planet [<class 'str'>]
Mass (10^24kg) [<class 'str'>]
Diameter (km) [<class 'str'>]
Density (kg/m^3) [<class 'str'>]
Gravity (m/s^2) [<class 'str'>]
Escape Velocity (km/s) [<class 'str'>]
Rotation Period (hours) [<class 'str'>]
Length of Day (hours) [<class 'str'>]
Distance from Sun (10^6 km) [<class 'str'>]
Perihelion (10^6 km) [<class 'str'>]
Aphelion (10^6 km) [<class 'str'>]
Orbital Period (days) [<class 'str'>]
Orbital Velocity (km/s) [<class 'str'>]
Orbital Inclination (deg) [<class 'str'>]
Orbital Eccentricity [<class 'str'>]
Obliquity to Orbit (deg) [<class 'str'>]
Mean Temperature (C) [<class 'str'>]
Surface Pressure (bars) [<class 'str'>]
Number of Moons [<class 'str'>]
Ring System? [<class 'str'>]
Global Magnetic Field? [<class 'str'>]

In [18]:
# (a) What types are the actual values? strings
# (b) Why is storing numeric values as strings a problem for data analysis? because you cannot do numerical operations with strings

In [19]:
cols_to_skip = ["Planet", "Ring System?", "Global Magnetic Field?"]

for col in df.columns:
    if col not in cols_to_skip:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [20]:
df.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [21]:
# the 3 different types of data are object, float64, int64
# 'Planet', 'Global Magnetic Field?', and 'Ring System?' are still objects because they are the only values that are not numerical values

In [22]:
def attach_units(old_col, new_col, unit):
    new_values = []
    for val in df[old_col]:
        new_values.append(val * unit)
    
    df[old_col] = new_values
    df.rename(columns={old_col: new_col}, inplace=True)

In [23]:
attach_units("Distance from Sun (10^6 km)", "Distance from Sun (km)", 1e6 * u.km)

In [24]:
print(df["Distance from Sun (km)"])

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384000.0 km
4     228000000.0 km
5     778500000.0 km
6    1432000000.0 km
7    2867000000.0 km
8    4515000000.0 km
9    5906400000.0 km
Name: Distance from Sun (km), dtype: object

In [29]:
print(type(df['Perihelion (10^6 km)'].iloc[0]))

<class 'numpy.float64'>

In [30]:
print(type(df['Aphelion (10^6 km)'].iloc[0]))

<class 'numpy.float64'>

In [ ]:
df['Semi-Major Axis (km)'] = (df['Perihelion (km)'] + df['Aphelion (km)']) / 2

In [ ]:
df

In [28]:
df.columns

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [107]:
print(df["Semi-Major Axis (km)"])

0             3.4900023e+25 km
1           5.445005375e+25 km
2           7.605007355e+25 km
3    2.0300018149999997e+23 km
4    1.2465010334999999e+26 km
5           4.082003703e+26 km
6           7.532506788e+26 km
7         1.50070136635e+27 km
8         2.27945223555e+27 km
9          3.6879522184e+27 km
Name: Semi-Major Axis (km), dtype: object

In [163]:
orbit_days = df['Orbital Period (days)'].values * u.day
orbit_in_years = orbit_days.to(u.year)
df['Orbital Period (years)'] = orbit_in_years.value
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (km),Perihelion (10^6 km),...,Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Orbital Period (years)
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57900000.0 km,46.000,...,47.4,7.0,0.206,0.034,167,0.00000,0,No,Yes,0.240931
1,Venus,4.870,12104,5243,8.9,10.4,-5832.5,2802.0,108200000.0 km,107.500,...,35.0,3.4,0.007,177.400,464,92.00000,0,No,No,0.615195
2,Earth,5.970,12756,5514,9.8,11.2,23.9,24.0,149600000.0 km,147.100,...,29.8,0.0,0.017,23.400,15,1.00000,1,No,Yes,0.999863
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,384000.0 km,0.363,...,1.0,5.1,0.055,6.700,-20,0.00000,0,No,No,0.074743
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228000000.0 km,206.700,...,24.1,1.8,0.094,25.200,-65,0.01000,2,No,No,1.880903
5,Jupiter,1898.000,142984,1326,23.1,59.5,9.9,9.9,778500000.0 km,740.600,...,13.1,1.3,0.049,3.100,-110,NaN,95,Yes,Yes,11.857632
6,Saturn,568.000,120536,687,9.0,35.5,10.7,10.7,1432000000.0 km,1357.600,...,9.7,2.5,0.052,26.700,-140,NaN,274,Yes,Yes,29.423682
7,Uranus,86.800,51118,1270,8.7,21.3,-17.2,17.2,2867000000.0 km,2732.700,...,6.8,0.8,0.047,97.800,-195,NaN,28,Yes,Yes,83.748118
8,Neptune,102.000,49528,1638,11.0,23.5,16.1,16.1,4515000000.0 km,4471.100,...,5.4,1.8,0.010,28.300,-200,NaN,16,Yes,Yes,163.723477
9,Pluto,0.013,2376,1850,0.7,1.3,-153.3,153.3,5906400000.0 km,4436.800,...,4.7,17.2,0.244,119.500,-225,0.00001,5,No,Unknown,247.939767

In [164]:
print(df['Orbital Period (years)'])

0      0.240931
1      0.615195
2      0.999863
3      0.074743
4      1.880903
5     11.857632
6     29.423682
7     83.748118
8    163.723477
9    247.939767
Name: Orbital Period (years), dtype: float64

In [171]:
favorite_planet = 'Earth'
period = df.loc[df['Planet'] == favorite_planet, 'Orbital Period (years)'].values[0]
print(f"\n{favorite_planet}'s orbital period: {period:.4f} years")

Earth's orbital period: 0.9999 years

In [3]:
# define AU- Astronomical Units are units of distance used to describe distances within our solar system. It’s defined as the average distance between the Earth and the Sun
print(const.au)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [5]:
print(const.au.to(u.km))

149597870.70000002 km

In [48]:
# 1 AU is approximately 149,597,870.7 kilometers

In [57]:
# km_cols = [col for col in df.columns if 'km' in col]
# for col in km_cols:
#     try:
#         values = df[col].to_numpy(dtype=float)
#         df[col] = (values * u.km).to(u.AU).value
#         df.rename(columns={col: col.replace('km', 'AU')}, inplace=True)
#     except Exception as e:
#         print(f"Skipping {col} due to error: {e}")

Skipping Distance from Sun (km) due to error: only dimensionless scalar quantities can be converted to Python scalars

In [59]:
km_cols = [col for col in df.columns if 'km' in col]

for col in km_cols:
    try:
        cleaned = (
            df[col]
            .astype(str)               
            .str.replace(',', '')      
            .str.replace(' km', '', case=False)  
            .str.strip()           
        )

        values = pd.to_numeric(cleaned, errors='coerce').to_numpy(dtype=float)

        df[col] = (values * u.km).to(u.AU).value

        df.rename(columns={col: col.replace('km', 'AU')}, inplace=True)

    except Exception as e:
        print(f"Skipping {col} due to error: {e}")

df.head()

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (AU/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (10^6 AU),...,Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Diameter (AU),Escape Velocity (AU/s),Perihelion (10^6 AU),Aphelion (10^6 AU),Orbital Velocity (AU/s)
0,Mercury,0.330,1.457319e-21,5429,3.7,2.874372e-08,1407.6,4222.6,0.387038,3.074910e-07,...,167,0.00,0,No,Yes,0.000033,2.874372e-08,3.074910e-07,4.665842e-07,3.168494e-07
1,Venus,4.870,3.615369e-21,5243,8.9,6.951971e-08,-5832.5,2802.0,0.723272,7.185931e-07,...,464,92.00,0,No,No,0.000081,6.951971e-08,7.185931e-07,7.279515e-07,2.339605e-07
2,Earth,5.970,3.810117e-21,5514,9.8,7.486738e-08,23.9,24.0,1.000014,9.833028e-07,...,15,1.00,1,No,Yes,0.000085,7.486738e-08,9.833028e-07,1.016726e-06,1.992007e-07
3,Moon,0.073,1.037955e-21,3340,1.6,1.604301e-08,655.7,708.7,0.002567,2.426505e-09,...,-20,0.00,0,No,No,0.000023,1.604301e-08,2.426505e-09,2.713942e-09,6.684587e-09
4,Mars,0.642,2.028717e-21,3934,3.7,3.342294e-08,24.6,24.7,1.524086,1.381704e-06,...,-65,0.01,2,No,No,0.000045,3.342294e-08,1.381704e-06,1.666468e-06,1.610985e-07

In [60]:
print(const.G)

  Name   = Gravitational constant
  Value  = 6.6743e-11
  Uncertainty  = 1.5e-15
  Unit  = m3 / (kg s2)
  Reference = CODATA 2018

In [69]:
M = df['Mass (10^24kg)'].values * 1e24 * u.kg

diam_au = np.array(df['Diameter (AU)']).astype(float)

if diam_au.ndim == 2:
    diam_au = diam_au[:, 0]

R = (diam_au / 2) * u.AU
R = R.to(u.m)

print(M.shape)
print(R.shape)

(10,)
(10,)

In [70]:
g = (const.G * M / R**2).to(u.m / u.s**2)
df['Surface Gravity (m/s^2)'] = g.value

In [71]:
df

,Planet,Mass (10^24kg),Diameter (AU),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (AU/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (10^6 AU),...,Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?,Diameter (AU),Escape Velocity (AU/s),Perihelion (10^6 AU),Aphelion (10^6 AU),Orbital Velocity (AU/s),Surface Gravity (m/s^2)
0,Mercury,0.330,1.457319e-21,5429,3.7,2.874372e-08,1407.6,4222.6,0.387038,3.074910e-07,...,0.00000,0,No,Yes,0.000033,2.874372e-08,3.074910e-07,4.665842e-07,3.168494e-07,1.853616e+33
1,Venus,4.870,3.615369e-21,5243,8.9,6.951971e-08,-5832.5,2802.0,0.723272,7.185931e-07,...,92.00000,0,No,No,0.000081,6.951971e-08,7.185931e-07,7.279515e-07,2.339605e-07,4.444659e+33
2,Earth,5.970,3.810117e-21,5514,9.8,7.486738e-08,23.9,24.0,1.000014,9.833028e-07,...,1.00000,1,No,Yes,0.000085,7.486738e-08,9.833028e-07,1.016726e-06,1.992007e-07,4.905832e+33
3,Moon,0.073,1.037955e-21,3340,1.6,1.604301e-08,655.7,708.7,0.002567,2.426505e-09,...,0.00000,0,No,No,0.000023,1.604301e-08,2.426505e-09,2.713942e-09,6.684587e-09,8.083149e+32
4,Mars,0.642,2.028717e-21,3934,3.7,3.342294e-08,24.6,24.7,1.524086,1.381704e-06,...,0.01000,2,No,No,0.000045,3.342294e-08,1.381704e-06,1.666468e-06,1.610985e-07,1.860831e+33
5,Jupiter,1898.000,4.270819e-20,1326,23.1,3.977329e-07,9.9,9.9,5.203951,4.950605e-06,...,NaN,95,Yes,Yes,0.000956,3.977329e-07,4.950605e-06,5.457297e-06,8.756809e-08,1.241334e+34
6,Saturn,568.000,3.600315e-20,687,9.0,2.373028e-07,10.7,10.7,9.572329,9.074995e-06,...,NaN,274,Yes,Yes,0.000806,2.373028e-07,9.074995e-06,1.007033e-05,6.484050e-08,5.227357e+33
7,Uranus,86.800,1.526854e-20,1270,8.7,1.423817e-07,-17.2,17.2,19.164711,1.826697e-05,...,NaN,28,Yes,Yes,0.000342,1.423817e-07,1.826697e-05,2.006312e-05,4.545519e-08,4.441599e+33
8,Neptune,102.000,1.479362e-20,1638,11.0,1.570878e-07,16.1,16.1,30.180911,2.988746e-05,...,NaN,16,Yes,Yes,0.000331,1.570878e-07,2.988746e-05,3.047436e-05,3.609677e-08,5.559887e+33
9,Pluto,0.013,7.096925e-22,1850,0.7,8.689963e-09,-153.3,153.3,39.481845,2.965818e-05,...,0.00001,5,No,Unknown,0.000016,8.689963e-09,2.965818e-05,4.930485e-05,3.141756e-08,3.079058e+32

In [75]:
df.to_csv("units.csv", index=False)